---
- hosts: web
  vars:
    service_name: httpd

  tasks:
  - name: Check Service
    service_facts:

  - name: Stop Service
    service:
      name: httpd
      state: stopped
    when: httpd + '.service' in services
